### ISSUE TITLE
invalid argument on connect attempt

### ISSUE THREAD

**Issue by hackervera** [caolan/cpm#1]
tyler@rww-ubuntu:~/tmp/spora$ cpm push http://tyler:*****@tyler.couchone.com/spora
Error: Error: EINVAL, Invalid argument
    at doConnect (net:820:19)
    at Client.connect (net:893:30)
    at Client._reconnect (http:984:10)
    at Client.request (http:1018:42)
    at [object Object].JSONClient (/usr/local/lib/node/cpm/couchdb.js:109:26)
    at [object Object].exists (/usr/local/lib/node/cpm/couchdb.js:162:10)
    at [object Object].ensureDB (/usr/local/lib/node/cpm/couchdb.js:56:10)
    at Object.putPackage (/usr/local/lib/node/cpm/transports/db.js:128:8)
    at /usr/local/lib/node/cpm/commands/push.js:41:20
    at /usr/local/lib/node/cpm/deps/async/lib/async.js:74:13
Failed

**Comment by caolan** [comment]
Thanks, it wasn't setting the default port number properly. duh! 

You should be able to push projects to couchone if you reinstall cpm. However, please be aware that cpm currently has a different format to the standard couchapp tool, so if you're trying to push couchappspora then it would need a package.json adding at least.

In the future I might add couchapp.json support, I'd just rather not have to support the macros for code insertion etc...

**Comment by hackervera** [comment]
We are converting couchappspora to cpm if we can get it working :)

**Comment by caolan** [comment]
Nice! :) I've been watching that project with interest, seems like such a good fit for couchdb and a great project for pushing the boundaries of couchapps.

If you need any help porting it then let me know. I'd like to make this process as easy as possible for people migrating...
